### ISSUE TITLE
Error when running on Linux:  I get following error, Failed to load dynamic library 'libduckdb.so'

### ISSUE THREAD

**Issue by akza07** [TigerEyeLabs/duckdb-dart#15]
```bash
➜  ollama-lib dart run
Building package executable... 
Built ollama_lib:ollama_lib.
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'libduckdb.so': libduckdb.so: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      _defaultOpen (package:dart_duckdb/src/ffi/load_library.dart:33:35)
#3      OpenDynamicLibrary.openDuckDB (package:dart_duckdb/src/ffi/load_library.dart:134:12)
#4      duckdb (package:dart_duckdb/dart_duckdb.dart:84:36)
#5      new ChatManager (package:ollama_lib/chat_manager.dart:8:16)
#6      main (file:///run/media/akza/Windows-SSD/Users/akza0/OneDrive/Desktop/Dart/ollama-lib/bin/ollama_lib.dart:72:19)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Snippet that's using the DuckDB

```dart
class ChatManager {
  final OllamaClient ollama;

  ChatManager(this.ollama) {
    final db = duckdb.open(":memory:");
    final connection = duckdb.connect(db);

    connection.execute('''
        CREATE TABLE users (id INTEGER, name VARCHAR, age INTEGER);
        INSERT INTO users VALUES (1, 'Alice', 30), (2, 'Bob', 25);
      ''');

    final result =
        connection.query("SELECT * FROM users WHERE age > 28").fetchAll();

    for (final row in result) {
      print(row);
    }

    connection.dispose();
    db.dispose();
  }
// ....
```

```yaml
# `pubscpec.yaml`

name: ollama_lib
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  dart_duckdb: ^1.1.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

```

OS: Fedora Linux 41 (KDE Plasma) x86_64
Kernel: Linux 6.12.11-200.fc41.x86_64

Let me know if I need to add anymore info for context.
